### ISSUE TITLE
Can't you specify the counter with crypto.createCipheriv?

### ISSUE THREAD

**Issue by ivan** [jrnewell/crypto-aes-ctr#2]
I figured I needed crypto-aes-ctr to do CTR in the middle of a file, but reading the OpenSSL source suggested that for CTR modes, the [IV is treated as the counter](https://github.com/openssl/openssl/blob/master/crypto/modes/ctr128.c#L62), in big-endian format.  Therefore, can't one just use the standard node/io.js APIs for this?  Please let me know if I missed something.

The last test here confirms that this works:

``` js
"use strict";

var crypto = require('crypto');
var assert = require('assert');

function test() {
    var cipher;
    var decrypted;
    var key = new Buffer('12300000000000045600000000000789', 'hex');
    var iv0 = new Buffer('00000000000000000000000000000000', 'hex');
    var iv1 = new Buffer('00000000000000000000000000000001', 'hex');

    // Test for exact ciphertext
    cipher = crypto.createCipheriv('aes-128-ctr', key, iv0);
    var text = 'Hello, world. This is a test string spanning multiple AES blocks.';
    var encrypted = cipher.update(new Buffer(text));
    assert(encrypted.toString('hex') == '5a4be59fb050aa6059075162597141e2ff2c99e3b7b968f3396d50712587640626719dc348cb5d966985eb7bb964e35bbe0dd77624386b875f46694a1e89b49ec2', encrypted.toString('hex'));

    // Test that encryption->decryption round-trips
    cipher = crypto.createCipheriv('aes-128-ctr', key, iv0);
    decrypted = cipher.update(encrypted);
    assert(decrypted.toString('utf-8') == text, decrypted.toString('utf-8'));

    // Test that we can decrypt the middle of the ciphertext with an incremented IV
    cipher = crypto.createCipheriv('aes-128-ctr', key, iv1);
    decrypted = cipher.update(encrypted.slice(16));
    assert(decrypted.toString('utf-8') == text.substr(16));
}

test();
```

**Comment by jrnewell** [comment]
I am by no means a crypto expert and it has been a while since I looked into this stuff.  I believe you are correct - that ctr mode just uses the initial IV  + offset as a counter.  I think when I originally wanted to use ctr mode I tried using the standard node.js crypto interface with an IV offset like you are doing in your example script.  However, for some reason, I wasn't able to get it to work reliably, so I just ended up make this ctr interface because it wasn't too hard once I dove into the openssl code (plus I wanted to try make a c++ node.js extension).  I am not sure if it was due to something I was doing wrong or if there was some issue with the version at the time.  However, if it is working for you - that is great.  No need to use this package then other than for simplicity.

As a side-note the only thing you should be overly cautious of when using ctr mode is to ensure that you don't reuse the same IV + counter and key.  I ended up using a random IV and randomly salted key using pbkdf2 for each file I encrypted.

**Comment by ivan** [comment]
Got it.  Thanks for the explanation!
