### ISSUE TITLE
Error duing install 

### ISSUE THREAD

**Issue by raed667** [jrnewell/crypto-aes-ctr#3]
When I try to install I get an error 
`npm ERR! Failed at the crypto-aes-ctr@1.0.1 install script 'node-gyp rebuild'.
`

**Comment by jrnewell** [comment]
Yeah, sorry.. I haven't really updated this for a newer version of node because it isn't really needed.  You can use the stock node encryption and just increment the IV vector if you want to "skip" to a block using aes-ctr.  This is the function I use:

``` js
function incrementBuffer(buf, cnt) {
  var i, len, mod;
  len = buf.length;
  i = len - 1;
  while (cnt !== 0) {
    mod = (cnt + buf[i]) % 256;
    cnt = Math.floor((cnt + buf[i]) / 256);
    buf[i] = mod;
    i -= 1;
    if (i < 0) {
      i = len - 1;
    }
  }
  return buf;
};

// ---
// generated by coffee-script 1.9.2
```

When I have time, I will see if I can quickly fix the installation errrors.  Otherwise I will update the README and package.json to say it is deprecated.
